# Generated by Django 3.2.7 on 2024-01-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('ip_info', models.JSONField()),
                ('screen_resolution', models.CharField(max_length=15)),
                ('timezone', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=100)),
                ('Sec_Ch_Ua', models.CharField(max_length=100)),
                ('Sec_Ch_Ua_Platform', models.CharField(max_length=100)),
                ('Sec_Ch_Ua_Mobile', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
