# Generated by Django 3.2.7 on 2026-09-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('ip_info', models.JSONField(blank=True, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=15, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('Sec_Ch_Ua', models.CharField(blank=True, max_length=100, null=True)),
                ('Sec_Ch_Ua_Platform', models.CharField(blank=True, max_length=100, null=True)),
                ('Sec_Ch_Ua_Mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
